tmux kill-session -t core
tmux kill-session -t tycho_description
tmux kill-session -t tycho_transform
tmux kill-session -t rs_camera_435
tmux kill-session -t rs_camera_415_1
tmux kill-session -t rs_camera_415_2
tmux kill-session -t azcam
tmux kill-session -t mocap
tmux kill-session -t ball_pub
